
{{- if  .Values.global.om.server.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{  .Release.Name  }}-srv
  labels: 
    app: newman-srv
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "newman.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        app: newman-srv
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "newman.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.server.repository }}:{{ .Values.server.tag | default .Chart.AppVersion }}"
          env:
          - name: NEWMAN_MONGO_DB_HOST
            value: {{ .Release.Name }}-mongodb
          - name: NEWMAN_MONGO_DB_NAME
            value: newman-db  
          - name: NEWMAN_SERVER_SPOTINST_TOKEN
            value:   
          - name: NEWMAN_SERVER_SPOTINST_ACCOUNT_ID
            value:      
          imagePullPolicy: {{ .Values.server.pullPolicy }}
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
            - name: https
              containerPort: 8443
              protocol: TCP
          # livenessProbe:
          #   httpGet:
          #     path: 127.0.0.1
          #     port: 
          # readinessProbe:
          #   httpGet:
          #     path: 
          #     port: 
          resources: 
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- end }}
