apiVersion: apps/v1
kind: Deployment
metadata:
  name: "{{  .Release.Name  }}-newman-agent"
  labels:
    app: newman
spec:
  spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "newman.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        app: newman
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "newman.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: newman-agent
          securityContext:  
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.agent.repository }}:{{ .Values.image.agent.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
          - containerPort: 80
          env:
          - name: NEWMAN_USER
            value: {{ .Values.agent.env.user }}
          - name: NEWMAN_PASSWORD
            value: {{ .Values.agent.env.password }}
          - name: NEWMAN_SERVER_HOST
            value: newman-server
          - name: NEWMAN_SERVER_PORT
            value: '8443'
          - name: NEWMAN_AGENT_HOME
            value: /home/xap-agent
          - name: NEWMAN_AGENT_CAPABILITIES
            value: {{ .Values.agent.env.capabilities }}
          - name: NEWMAN_AGENT_WORKERS
            value: {{ .Values.agent.env.workers }}
          - name: NEWMAN_AGENT_GROUPNAME
            value: {{ .Values.agent.env.group }}
          - name: NEWMAN_NEWMAN_SRV_SERVICE_HOST
            value: newman-server
          - name: XAP_NEWMAN_AGENT_PORT_443_TCP_ADDR
            value: '443' 
          - name: NEWMAN_NEWMAN_SRV_PORT_8443_TCP
            value: '8443'
          volumeMounts:
            - mountPath: /home/xap-agent
              name: newman-data
          # command: ['mkdir', '-p', '/home/xap-agent']
      volumes:
        - name: newman-data
          persistentVolumeClaim:
            claimName: "{{  .Release.Name  }}-data"