nexus:
  readinessProbe:
    initialDelaySeconds: 90
  
  properties:
    override: false
    data:
      nexus.scripts.allowCreation: true
  env:
    - name: install4jAddVmParams
      value: "-Xms1200M -Xmx1200M -XX:MaxDirectMemorySize=2G -XX:+UnlockExperimentalVMOptions -XX:+UseCGroupMemoryLimitForHeap"
    - name: NEXUS_SECURITY_RANDOMPASSWORD
      value: "false"
  securityContext:
    fsGroup: 1001
  
  # Uncomment and modify this to run a command after starting the nexus container.
deployment:

  initContainers:
  - name: fmp-volume-permission
    image: busybox
    imagePullPolicy: IfNotPresent
    command: ['chown','-R', '200', '/nexus-data']
    volumeMounts:
    - mountPath: /nexus-data
      name: nexus-repository-manager-data
  - name: run-script
    image: busybox
    imagePullPolicy: IfNotPresent
    command: ['chown','-R', '200', '/nexus-data']
    volumeMounts:
    - mountPath: /nexus-data
      name: nexus-repository-manager-data

    
    
  # Uncomment and modify this to run a command after starting the nexus container.
  
  
  # postStart:
  #   command:
  #   - /bin/bash
  #   - /scripts/postStart.sh
secret:
  enabled: true
  mountPath: /etc/secret-volume/
  readOnly: true
  data: 
    password : |
      R2lnYVNwYWNlcw==

service:
  name: nexus3
  enabled: true
  labels: {}
  annotations: {}
  type: ClusterIP

resources:
  requests:
      ## Based on https://support.sonatype.com/hc/en-us/articles/115006448847#mem
      ## and https://twitter.com/analytically/status/894592422382063616:
      ##   Xms == Xmx
      ##   Xmx <= 4G
      ##   MaxDirectMemory >= 2G
      ##   Xmx + MaxDirectMemory <= RAM * 2/3 (hence the request for 4800Mi)
      ##   MaxRAMFraction=1 is not being set as it would allow the heap
      ##     to use all the available memory.
    cpu: 1Gi
    memory: 4800Mi

config:
  enabled: true
  data:
    postStart.sh: |-
      #!/bin/bash
      echo 'in script'
      set -eu
      HOST="localhost:8081"
      until curl --output /dev/null --silent --head --fail http://${HOST}/; do
      printf '.'
      sleep 5
      done
      NEXUS_BASE_DIR="/sonatype-nexus-conf"
      USERNAME="admin"
      PASSWORD="admin123"
      PASSWORD_FROM_FILE="$(cat /nexus-data/config/password || true)"
      function die() {
        echo "ERROR: $*" 1>&2
        exit 1
      }
      # Call the Nexus API for the specified repository
      function runCurlFromJsonFile() {
      local jsonFile
      local service
      local body
      local method
      jsonFile="${1}"
      service="${2}"
      method="${3}"
      body="$(cat "${jsonFile}")"
      if  ! curl --fail -X "${method}" -u "${USERNAME}":"${PASSWORD}" "http://${HOST}/${service}" -H "accept:application/json" -H "Content-Type:application/json" -d "${body//[$'\t\r\n']}"; then
      echo "Error calling Nexus API for http://${HOST}/${service} to add repository from ${jsonFile}"
      fi
      }
      
      
      function setPasswordFromFile() {
      if [ -n "${PASSWORD_FROM_FILE}" ]; then
          echo "Updating PASSWORD variable from password file."
          PASSWORD="${PASSWORD_FROM_FILE}"
      else
          echo "Not updating PASSWORD var. Password file either non-existent or not readable."
      fi
      }

      if curl --fail --silent -u "${USERNAME}":"${PASSWORD}" http://"${HOST}"/service/metrics/ping; then
          echo "Login to nexus succeeded. Default password worked. Updating password if available..."
          curl --fail -X PUT -u "${USERNAME}":"${PASSWORD}" "http://${HOST}/service/rest/beta/security/users/admin/change-password" --header "Content-Type: text/plain" -d "${PASSWORD_FROM_FILE}"
          setPasswordFromFile
      elif [ -n "${PASSWORD_FROM_FILE}" ]; then
          setPasswordFromFile
          echo "Default password failed. Checking password file..."
          if curl --fail --silent -u "${USERNAME}":"${PASSWORD}" http://"${HOST}"/service/metrics/ping; then
              echo "Login to nexus succeeded. Password from secret file worked."
          else
              die "Login to nexus failed. Tried both the default password and the provided password secret file."
          fi
      else
          die "Login to nexus failed. Tried the default password only since no password secret file was provided."
      fi 

