apiVersion: v1
kind: Secret
metadata:
  name: aws-s3-secret-key
  labels:
    app.kubernetes.io/part-of: jenkins-controller
    app.kubernetes.io/component: aws-s3-secret
    app.kubernetes.io/managed-by: Helm
  annotations:
    che.eclipse.org/automount-workspace-secret: 'true'
    che.eclipse.org/mount-path: /run/secrets/
    che.eclipse.org/mount-as: file
data:
  password: |
    UnNWRXp2R1lrNzFTb0RDUkYzZWJPOEQ4QTNVR0U2TnRTbUt6UE9qSw==