apiVersion: batch/v1
kind: Job
metadata:
  name: "{{ .Release.Name }}-postinstall-nexus"
  labels:
    app.kubernetes.io/managed-by: {{ .Release.Service | quote }}
    app.kubernetes.io/instance: {{ .Release.Name | quote }}
    app.kubernetes.io/version: {{ .Chart.AppVersion }}
    helm.sh/chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
  annotations:
    # This is what defines this resource as a hook. Without this line, the
    # job is considered part of the release.
    "helm.sh/hook": post-install
    "helm.sh/hook-weight": "-5"
    "helm.sh/hook-delete-policy": hook-succeeded
spec:
  template:
    spec:
      containers:
      - name: post-install-nexus-job
        image: ellerbrock/alpine-bash-curl-ssl
        imagePullPolicy: IfNotPresent
        volumeMounts:
          - name: config-volume
            mountPath: /sonatype-nexus-conf
          - name: nexus-data
            mountPath: /nexus-data
          - name : scripts
            mountPath: /scripts

        command: 
          - sh
          - -c
          - >
            mkdir -p -m 0777 /scripts;
            ls -l;
            ls -l /sonatype-nexus-conf;
            cat /sonatype-nexus-conf/postStart.sh >/scripts/postStart.sh;
            chmod 777 /scripts/postStart.sh;
            ls -la /scripts;
            /scripts/postStart.sh;
            sleep 50
            
      volumes:
        - name: config-volume
          configMap:
            name: {{ .Release.Name }}-postinstall-nexus-configmap
            defaultMode: 0777
        - name: scripts
          emptyDir: {}
        - name: nexus-data
          emptyDir: {}  
        - name: sonatype-nexus-conf
          emptyDir: {}       
      restartPolicy: Never
      terminationGracePeriodSeconds: 0
  