apiVersion: v1
kind: Secret
metadata:
  name: smtp-secret
  labels:
    app.kubernetes.io/part-of: jenkins-controller
    app.kubernetes.io/component: smtp-secret
    app.kubernetes.io/managed-by: Helm
  annotations:
    che.eclipse.org/automount-workspace-secret: 'true'
    che.eclipse.org/mount-path: /run/secrets/
    che.eclipse.org/mount-as: file
data:
  password: |
    QktDMnF1UXIwL09tRklpNlh1WFQ0OUViNVZIRzlKL1BwYTN0ZDhha3FTaUc=
    