apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: loki-stack
  namespace: argocd
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
  source:
    chart: loki-stack
    repoURL: https://grafana.github.io/helm-charts
    targetRevision: 2.3.0
    helm:
      values: |
        loki:
          # intentional
          persistence:
            enabled: false
            # accessModes:
            # - ReadWriteOnce
            # size: 20Gi
          serviceMonitor:
            enabled: true
            additionalLabels: 
              release: prometheus-operator
            annotations: {}
