apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: {{ .Release.Namespace }}
  name: jenkins-aws-eks-role
rules:
rules:
- apiGroups:
  - '*'
  resources:
  - statefulsets
  - services
  - services/proxy
  - replicationcontrollers
  - replicasets
  - podtemplates
  - podsecuritypolicies
  - pods
  - pods/log
  - pods/exec
  - podpreset
  - poddisruptionbudget
  - persistentvolumes
  - persistentvolumeclaims
  - jobs
  - endpoints
  - deployments
  - deployments/scale
  - daemonsets
  - cronjobs
  - configmaps
  - namespaces
  - events
  - secrets
  verbs:
  - create
  - get
  - watch
  - delete
  - list
  - patch
  - update
- apiGroups:
  - ""
  resources:
  - nodes
  verbs:
  - get
  - list
  - watch
  - update
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
    name: {{.Release.Name}}-jenkins-aws-eks
    namespace: {{ .Release.Namespace }}
    labels:
        app.kubernetes.io/name: {{.Release.Name}}
        helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version }}
        app.kubernetes.io/managed-by: {{ .Release.Service }}
        app.kubernetes.io/instance: {{ .Release.Name }}
        release: {{ .Release.Name }}
roleRef:
    apiGroup: rbac.authorization.k8s.io
    kind: Role
    name: jenkins-aws-eks-role
subjects:
    - kind: ServiceAccount
      name: jenkins-aws-eks
      namespace: {{ .Release.Namespace }}
