apiVersion: v1
kind: Secret
metadata:
  name: gigaci-mongodb
  labels:
    app.kubernetes.io/part-of: mongodb
    app.kubernetes.io/component: workspace-secret
    app.kubernetes.io/managed-by: Helm
  annotations:
    che.eclipse.org/automount-workspace-secret: 'true'
data:
   mongodb-root-password: |  
    bW9uZ29kYg==